[General]
key_pmi=6607573167
key_pmi_invite_msg="Alex Day is inviting you to a scheduled Zoom meeting.\r\n\r\nTopic: Alex Day's Personal Meeting Room\r\n\r\nJoin Zoom Meeting\r\nhttps://zoom.us/j/6607573167?pwd=MUFBUm1sTDR0N2tCRVpVQ1B1MUtkZz09\r\n\r\nMeeting ID: 660 757 3167\r\nPassword: 1i3JDs\r\n"
