# vim: filetype=sh
abbr h "cd ~/; and ls -a"
abbr d "cd ~/doc; and ls -a"
abbr D "cd ~/dl; and ls -a"
abbr cf "cd ~/.config; and ls -a"
abbr b "cd ~/.local/bin; and ls -a"
abbr mn "cd /mnt; and ls -a"
abbr r "cd ~/code/repos; and ls -a"
abbr bf "$EDITOR ~/.config/files"
abbr bd "$EDITOR ~/.config/directories"
abbr bw "$EDITOR ~/.config/bookmarks"
abbr cfa "$EDITOR ~/.config/aliasrc"
abbr cfv "$EDITOR ~/.config/nvim/init.vim"
abbr cfm "$EDITOR ~/repos/dmenu/config.h"
abbr cfd "$EDITOR ~/.config/dunst/dunstrc"
abbr cfs "$EDITOR ~/repos/slstatus/config.h"
abbr cfk "$EDITOR ~/.config/sxhkd/sxhkdrc"
abbr cff "$EDITOR ~/.config/fish/config.fish"
abbr cfc "$EDITOR ~/.config/picom/picom.conf"
abbr cfr "$EDITOR ~/.config/ranger/rc.conf"
abbr cfo "$EDITOR ~/.config/offlineimap/config"
