# vim: filetype=sh
abbr h "cd ~/; and ls -a"
abbr d "cd ~/Documents; and ls -a"
abbr D "cd ~/Downloads; and ls -a"
abbr m "cd ~/Music; and ls -a"
abbr pp "cd ~/Pictures; and ls -a"
abbr vv "cd ~/Videos; and ls -a"
abbr cf "cd ~/.config; and ls -a"
abbr sc "cd ~/.local/bin; and ls -a"
abbr mn "cd /mnt; and ls -a"
abbr b "cd ~/Documents/books; and ls -a"
abbr bf "$EDITOR ~/.config/files"
abbr bd "$EDITOR ~/.config/directories"
abbr bw "$EDITOR ~/.config/bookmarks"
abbr cfa "$EDITOR ~/.config/aliasrc"
abbr cfv "$EDITOR ~/.config/nvim/init.vim"
abbr cfm "$EDITOR ~/repos/dmenu/config.h"
abbr cfd "$EDITOR ~/repos/dwm/config.h"
abbr cfs "$EDITOR ~/repos/slstatus/config.h"
abbr cfk "$EDITOR ~/.config/sxhkd/sxhkdrc"
abbr cff "$EDITOR ~/.config/fish/config.fish"
