map gh cd ~/
map th tab_new ~/
map mh shell mv -v %s ~/
map Yh shell cp -rv %s ~/
map gd cd ~/doc
map td tab_new ~/doc
map md shell mv -v %s ~/doc
map Yd shell cp -rv %s ~/doc
map gD cd ~/dl
map tD tab_new ~/dl
map mD shell mv -v %s ~/dl
map YD shell cp -rv %s ~/dl
map gcf cd ~/.config
map tcf tab_new ~/.config
map mcf shell mv -v %s ~/.config
map Ycf shell cp -rv %s ~/.config
map gb cd ~/.local/bin
map tb tab_new ~/.local/bin
map mb shell mv -v %s ~/.local/bin
map Yb shell cp -rv %s ~/.local/bin
map gmn cd /mnt
map tmn tab_new /mnt
map mmn shell mv -v %s /mnt
map Ymn shell cp -rv %s /mnt
map gr cd ~/code/repos
map tr tab_new ~/code/repos
map mr shell mv -v %s ~/code/repos
map Yr shell cp -rv %s ~/code/repos
map bf shell $EDITOR ~/.config/files
map bd shell $EDITOR ~/.config/directories
map bw shell $EDITOR ~/.config/bookmarks
map cfa shell $EDITOR ~/.config/aliasrc
map cfv shell $EDITOR ~/.config/nvim/init.vim
map cfm shell $EDITOR ~/repos/dmenu/config.h
map cfd shell $EDITOR ~/.config/dunst/dunstrc
map cfs shell $EDITOR ~/repos/slstatus/config.h
map cfk shell $EDITOR ~/.config/sxhkd/sxhkdrc
map cff shell $EDITOR ~/.config/fish/config.fish
map cfc shell $EDITOR ~/.config/picom/picom.conf
map cfr shell $EDITOR ~/.config/ranger/rc.conf
map cfo shell $EDITOR ~/.config/offlineimap/config
