#! /usr/bin/env sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

remaps &		                    # run the remaps script, switching caps/esc and more
picom --config ~/.config/picom/picom.conf & # picom (nee compton) for transparency
dunst &			                    # dunst for notifications
sxhkd -m 1 &		                    # Bind keys with sxhkd
xset r rate 300 50 &	                    # Speed xrate up
unclutter &		                    # Remove mouse when idle
xss-lock -- fancy-slock & 		    # Set a lock screen
autorandr --load main &   		    # Load the default screen configuration
setbg ~/.config/wall.png &		    # set the background with the `setbg` script
$STATUSBAR &		                    # script for updating the status bar
emacs --daemon & 		            # Start emacs
dropbox start &                             # Start dropboxd
