;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
;;
;;	   ______      __
;;	  / ____/___  / /___  __________
;;	 / /   / __ \/ / __ \/ ___/ ___/
;;	/ /___/ /_/ / / /_/ / /  (__  )
;;	\____/\____/_/\____/_/  /____/
;;
;; Created By Aditya Shakya @adi1090x
;;
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[color]

;; Active Colors
bg = #282828
fg = #1C1E20
fg-alt = #EBDBB2
mf = #EBDBB2
ac = #458588

;; Bars
bn = #308634
bm = #E57C46
bd = #E24C49

trans = #00000000
white = #FFFFFF
black = #000000

;; Colors

red = #CC241D
pink = #EC6798
purple = #B16286
blue = #458588
cyan = #83A598
teal = #00B19F
green = #98971a
lime = #B9C244
yellow = #D79921
amber = #EDB83F
orange = #D65D0E
brown = #AC8476
grey = #928374
indigo = #6C77BB
blue-gray = #6D8895

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
;;	    __________  ______
;;	   / ____/ __ \/ ____/
;;	  / __/ / / / / /_
;;	 / /___/ /_/ / __/
;;	/_____/\____/_/
;;
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
